### PR TITLE
Redox OS

### PR DESCRIPTION
**Pull request by ids1024**

### CODE REVIEW

**Comment by ids1024** [comment]
Ping @brson

**Comment by jackpot51** [comment]
@alexcrichton could you take a look at this?

**Comment by alexcrichton** [comment]
Sorry, but I don't maintain this crate

**Comment by jackpot51** [comment]
Who maintains it now? Is it still being used by cargo and rustc?

**Comment by brson** [comment]
This is published as 0.3.4. Thanks.

If anybody wants to be a maintainer of this crate they are welcome.

**Comment by jackpot51** [comment]
Thank you @brson

**Pull request merged**
